### ISSUE TITLE
Dequeue of select2 scripts

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/ultimatemember#1088]
**Is your feature request related to a problem? Please describe.**
Current filter hook `um_dequeue_select2_scripts` only allows to dequeue select2 scripts with the handle name `select2`

**Describe the solution you'd like**
Search for script names to dequeue where name contains select2.

**Describe alternatives you've considered**
Code snippet in the filter hook that is performing the dequeue.

```
add_filter( 'um_dequeue_select2_scripts', 'um_dequeue_select2_scripts_fix', 10, 1 );
function um_dequeue_select2_scripts_fix( $bool ) {
    wp_dequeue_style( 'select2' );
    wp_deregister_style( 'select2' );
    wp_dequeue_script( 'select2.min.js');
    wp_deregister_script('select2.min.js');
    return $bool;
}
```

**Additional context**
UM Support Forum issue https://wordpress.org/support/topic/select2-conflicts/

How to search for enqueued scripts see 
https://docs.ultimatemember.com/article/1490-how-to-remove-css-and-js-on-non-um-pages

**Comment by nikitasinelnikov** [comment]
Hi @MissVeronica 

The `um_dequeue_select2_scripts` hook works like a bool logic value (Dequeue = Yes||No). Users|Developers can use the workaround you shared above with their own dequeue handles.

Since UMv3 we are planning to move forward without the select2 library to avoid conflicts with themes and 3rd-party plugins that use the select2 library.

For now, developers or customers can deregister|dequeue scripts and styles themselves via the custom callback function before UM styles and scripts are enqueued. (We use 100 priority by default, so callback on the standard 'wp_enqueue_scripts' hook with 99 priority gets a trick).

Thanks for letting us know,
Best Regards!

**Comment by MissVeronica** [comment]
We have heard about UM V3 for a long time now, when will this version be released?

**Comment by nikitasinelnikov** [comment]
Some major stuff will be finished this year. Based on this, the next steps will be clear. There is an approximate ETA that a public demo for v3 will be ready in a few months. In any case, you can get the latest changes from the `development/3.0` branch
