### ISSUE TITLE
Fixed WPML Compatibility and provide greater documentation

### ISSUE THREAD

**Issue by champsupertramp** [ultimatemember/ultimatemember#112]
- Add fallback for `ultimate-member` text domain
- Fix WPML compatibility with third-party plugins
- Provide greater documentation / guides

**Comment by bizzthemes** [comment]
Sounds great ;) Let me know if you need any help.

**Comment by champsupertramp** [comment]
Please download the pre-release version: https://github.com/ultimatemember/ultimatemember/releases/tag/v1.3.45

and read the integration guide: http://docs.ultimatemember.com/article/193-wpml-integration

Regards,

**Comment by bdgeyter** [comment]
After some trial and error, I think I figured out that you need to translate Forms like any other post type and then copy the new shortcode to the corresponding translated page. Maybe you can add that to the docs, because that wasn't clear to me at first. 

This sentence especially lead me in the wrong direction: 

> Also, If there are dynamic strings that need to be translated, you will need the WPML String Translation plugin to translate them

Also, currently there's no `wpml-config.xml` if I'm not mistaken, which meant that Forms wasn't marked as Translate by default in the WPML Admin.

Now also none of the styling of forms (post_meta) is being copied to the translated form.

**Comment by nomad411** [comment]
So, is UM finally fully WPML compatible?

**Comment by champsupertramp** [comment]
Hi @bdgeyter @nomad411,
We are still improving Ultimate Member to be fully compatible with WPML plugin.  Thanks for letting us know. 

Regards,

**Comment by Patresko** [comment]
WPML conflict with HTML email. While is WPML activated HTML from UM doesnt work.
