### ISSUE TITLE
Any user role other than admin can't access wp-admin

### ISSUE THREAD

**Issue by joshuakern** [ultimatemember/ultimatemember#364]
### Ultimate Member Version
Tell us what UM core version you use. 
- [] 1.3.88 ( latest )
- [x] 2.0 ( beta )

### Subject of the issue
User roles, except admin, can't access wp-admin, even when **Can access wp-admin?** is selected.

### Expected behavior
I expect the **Can access wp-admin?** checkbox to grant access to the admin area.

### Actual behavior
I see the admin bar at the top of the screen, but when I click to access the backend, the page refreshes, and I stay on the frontend.

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by nikitasinelnikov** [comment]
Hi @joshuakern 

Sorry for delay, please upgrade your UM to the latest version from "master" branch. There was added some fixes at the latest commits. Please let me know how it works after upgrade.

Thanks!

**Comment by Prawny** [comment]
This bug is either not fixed or has resurfaced.

I have a website with 4 UM user roles, 3 of which require access to /wp-admin. They all used to be able to access the admin area fine, but all of a sudden any attempt to access it redirects back to the home page for any type of user apart from core WP administrator.

Disabling the "can access wp-admin" setting, updating the role, re-enabling the setting and updating once more does not fix the problem for any user roles.

I have tested this on both production and local versions and the same exact thing happens.

UM version 2.0.22 (was not working prior to this version either)

No UM add-ons in use. The issue still exists with no other plugins enabled.

**Comment by gooner86** [comment]
I'm also seeing this issue. Version 2.0.29. Users with roles who need to access wp-admin are being redirected to the homepage or their profile page.
