### ISSUE TITLE
User role dependent on user input during registration

### ISSUE THREAD

**Issue by stefahn** [ultimatemember/ultimatemember#380]
In our registration we have a certain field. If the user fills out this field he should become part of group A. If he doesn't fill out the field he should become part of group B. 

I checked http://docs.ultimatemember.com/article/89-conditional-logic but it doesn't seem to cover this.

Is it possible with UM 1.3.88 and/or UM 2.0 - or with an extension (for example User tags)?
If not, I would like to suggest this as a feature request.

**Comment by nikitasinelnikov** [comment]
Hi @stefahn 

Since UM2.0 version there is possible to insert "User Role" field to registration form. You can use custom CSS and JS for implement your logic at your site. 

For example:
1) Place "User Role (dropdown)" field at your Registration form;
2) Hide this field using custom CSS;
3) Make custom JS like this:

jQuery(document).ready( function() {
 jQuery('user fill this field selector').change(function(){
   if( jQuery(this).val() == 'group A' )
         jQuery('role field selector').val( 'group A' ); 
   else 
        jQuery('role field selector').val( 'group B' );
 });
})

4) Enqueue custom JS and CSS in functions.php at your child theme or write custom plugin

Thanks!
