### ISSUE TITLE
Fields aren't serialized before checking if they match existing value on profile edit

### ISSUE THREAD

**Issue by treechime** [ultimatemember/ultimatemember#383]
### Ultimate Member Version
2.0 ( beta )

### Subject of the issue
`um_user_edit_profile()` on line 45 in `um-actions-profile.php` doesn't correctly compare values to see what profile fields have changed when updating.

### Expected behavior
`$to_update` should contain only fields that have changed

### Actual behavior
`$to_update` contains fields that have changed as well as any field that returns an array, as the arrays haven't been serialized before being checked against existing values and therefore automatically don't match.

### Steps to reproduce the behavior
Have field that produces an array value (etc multiselect field) and edit profile. If using hook like `um_user_after_updating_profile` for example, the `$to_update` variable passed to the hook contains unedited fields.

**Comment by nikitasinelnikov** [comment]
Hi @treechime 

Please provide where is this line now at "master" branch. There was many updates since 1 Feb. Also $to_update is array of the fields, which are upgraded on Profile submit. Radio, checkbox fields with empty values are deleted from usermeta and there are not this fields at $to_update array.

Please let me know
Thanks!
