### ISSUE TITLE
Menu issue for logged out user ?

### ISSUE THREAD

**Issue by dotMastaz** [ultimatemember/ultimatemember#435]
### Ultimate Member Version
Tell us what UM core version you use. 
- [x] 2.0.13 ( latest )
- [ ] 2.0 ( beta )

### Subject of the issue
Menus are ok for connected user, but not for logged out ?

Any ideas ?

thank you !

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce the behavior
Tell us how to reproduce this issue. 

## PHP version
- [x] 7.1 above
- [ ] 5.4 
- [ ] 5.3 below

### Do you use UM extensions? 
- [ ] Private Content 
- [ ] Instagram
- [ ] User Tags 
- [ ] Social Activity
- [ ] WooCommerce
- [ ] Private Messages
- [ ] Followers
- [ ] Real-time Notifications
- [ ] Social Login
- [ ] bbPress
- [ ] MailChimp
- [ ] User Reviews
- [ ] Verified Users
- [ ] myCRED
- [ ] Notices
- [ ] Profile Completeness 
- [ ] Friends
- [ ] Terms & Conditions
- [ ] Google reCAPTCHA 
- [ ] Online Users

**Comment by torreyj** [comment]
I'm having the same issue. My menu is not registering any UM condition

**Comment by bennyboyworld** [comment]
**Same issue. Ultimate Member Menu Role Problem ** 

Just to clarify:

1. "If user is logged in" or "If user is logged out" dropdown select in Appearances >> Menu > Item is: WORKING. This chooses to show an item if the user is logged in or not.

2. Ticking a user role AND selecting "If user is logged in". NOT WORKING.

Any support you can give for 2. is appreciated. Thanks

**Comment by dcmcshan** [comment]
I have this same issue as well.  Have reproduced it using 2.0.17 
- with stock 2017 theme with no plugins active, menus work (4 custom link menus)
- with just UM plugin activated, menus are corrupt (only the third menu shows)

Menus are very simple, no conditionals are used.

I can easily reproduce if you'd like to see it.

**Comment by bennyboyworld** [comment]
@dcmcshan ... Hey Dan, I upgraded UM and now the Appearance >> Menu  options are for "For Logged In Users" and "For Logged Out Users". I can't choose which users groups can see which menu element under Appearances >> Menus (anymore since upgrading to the latest UM version).

I didn't try and find a work around... for my premium members - they're seeing the [Upgrade your account button]. I guess I could hide it with a css class, but I was anticipating a fix to be released soon and I didn't want to hack my site.... ?

**Same issue. Ultimate Member Menu Role Problem **

Anyone got a solution> - I haven't tried to find a menu role plugin, there might be one that works, outside the scope of UM.
