### ISSUE TITLE
Security issue: Low-level users can edit/delete all other users, even admins!

### ISSUE THREAD

**Issue by stefahn** [ultimatemember/ultimatemember#536]
The following settings have no effect:
- Can edit these user roles only
- Can delete these user roles only

In our case editors should only be able to edit and delete subscribers. But in fact they can edit admins or even remove admins!!

Under "WP Capabilities" those relevant entries are checked for our editors: edit_users, delete_users, list_users.

Using Ultimate Member 2.0.29 (latest) with no other UM extensions.

See also #479 , #480 , #481 , #482 , #483 , which apparently were not fixed.

**Comment by denisbaranov** [comment]
This bug should be fixed in the next release. See branch [fix/github#536_use_roles_priority_for_option__can_edit_these_user_roles_only](https://github.com/ultimatemember/ultimatemember/tree/fix/github%23536_use_roles_priority_for_option__can_edit_these_user_roles_only)

Note: Users in WordPress may have several roles. Please use "Role Priority" option to avoid role conflicts. For example you may set priority:

- 30 for admins
- 20 for editors
- 10 for subscribers
- 0 for all other roles
