### ISSUE TITLE
Hide on Member Directory

### ISSUE THREAD

**Issue by hirenshah** [ultimatemember/ultimatemember#622]
After the recent update, all members who had their profile visible on the directory have to toggle that option to make their profile cards show up on the directory.

**Comment by hirenshah** [comment]
Actually figured out that this meta was added and until someone updates something on their account, it is missing and therefore their profile card does not show in the directory:
um_member_directory_data

**Comment by nikitasinelnikov** [comment]
Hi @hirenshah 

There was added a fix for that. Please update this option 'um_last_version_upgrade' in DB to '2.1.0-beta1' and re-run upgrade for 2.1.3-beta3 version. You will see admin notice in wp-admin screen,

Let me know if that works,
Thanks!

**Comment by hirenshah** [comment]
@nikitasinelnikov Ahh, so I didn't know that that was how you could force the Upgrade DB option to reappear. Is there a document where that is mentioned? I could find one, so if there isn't, please create one.

I had fixed the issue "manually" but will restore a backup and do it the proper way 🙂

**Comment by nikitasinelnikov** [comment]
Hi @hirenshah 

This option  'um_last_version_upgrade' is created for the internal plugin use. Just there aren't data moving or delete, just create meta rows from existed in the current DB upgrade (2.1.3-beta3). Otherwise, it could lead to unexpected consequences

We highly recommend making backup before every update and rolling back if there were some issues with upgrade.

Thanks for letting me know, could I close this issue?

Best Regards!
