### ISSUE TITLE
Ultimate member unable to make new registrations

### ISSUE THREAD

**Issue by willral** [ultimatemember/ultimatemember#652]
Fatal error: Uncaught Error: Call to undefined function utf8_decode() in /var/www/html/wp-content/plugins/ultimate-member/includes/core/um-actions-form.php:508 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(288): um_submit_form_errors_hook_(Array) #1 /var/www/html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #2 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /var/www/html/wp-content/plugins/ultimate-member/includes/core/um-actions-form.php(236): do_action('um_submit_form_...', Array) #4 /var/www/html/wp-includes/class-wp-hook.php(288): um_submit_form_errors_hook(Array) #5 /var/www/html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #6 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #7 /var/www/html/wp-content/plugins/ultimate-member/includes/core/class-form.php(459): do_action('um_submit_form_...', Array) #8 /var/www/html/wp-includes/class-wp-hook.php(288): um\core\Form->form_init('') #9 /var/www/html/wp-includes/clas in /var/www/html/wp-content/plugins/ultimate-member/includes/core/um-actions-form.php on line 508

**Comment by champsupertramp** [comment]
Hi @willral 

Run `php -v` to check the version of PHP.

If you're running version is 5.6, the solution is as follows:

`sudo apt-get install php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-xml`

Otherwise, run the following:

`sudo apt-get install php7.2-mbstring php7.2-mcrypt php7.2-mysql php7.2-xml`

Or ask your hosting provider to assist you with the server-side issue.

Regards,

**Comment by willral** [comment]
thanks this worked i upgraded to 7.4 instead
