### ISSUE TITLE
Admins unable to edit user profiles after 2.1.9 update if Role field is present

### ISSUE THREAD

**Issue by justdave** [ultimatemember/ultimatemember#670]
**Expected behavior**
Admins should be able to edit user profiles.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [X] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [X] I can reproduce this bug consistently using the steps above.

**Describe the bug**
After updating to version 2.1.9, attempting to edit a user profile while logged into an admin account when a Role field is present results in "This is not possible for security reasons."
Users who are not admins can update their own profiles just fine (because they can't see the Role field).
Rolling back to version 2.1.8 makes the error go away and profiles can be edited.

**To Reproduce**
1. Set up a profile form that includes the Role field (either dropdown or radio buttons, the same behavior affects both). Make sure the field is set up to only be viewable/editable by Administrator.
2. Visit any user's profile who would use that profile form.
3. Edit the profile.
4. Save the profile (doesn't matter if you change anything or not)
5. View error message "This is not possible for security reasons."

**Expected behavior**
Changes to the profile should save.

**Screenshots**
n/a

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce
- [x] none of the above

**WordPress Environment**
<details>

``` 

### Begin Install Info ###

## Please include this information when posting support requests ##


--- Site Info ---

Site URL:					https://(redacted)
Home URL:					https://(redacted)
Multisite:					No

--- Hosting Provider ---

Host:						DBH: (redacted), SRV: (redacted)

--- User Browser ---

Platform:                 Apple 
Browser Name:             Firefox  
Browser Version:          81.0 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10.15; rv:81.0) Gecko/201
                          00101 Firefox/81.0
                          
---- Current User Details --

Role: administrator, um_volunteer


--- WordPress Configurations ---

Version:						5.5.1
Language:					en_US
Permalink Structure:			/%postname%/
Active Theme:				GRYS 1.0
Page On Front:				GRYS & CO Members Only (#13)
Page For Posts:				 (#0)
ABSPATH:					/home/grys/(redacted)/
All Posts/Pages:				4
WP Remote Post:           		wp_remote_post() works
WP_DEBUG:                 			Enabled
WP Table Prefix:          			Length: 3, Status: Acceptable
Memory Limit:   				40MB


--- UM Configurations ---

Version:						2.1.8
Upgraded From:            		2.1.5
Current URL Method:			
Cache User Profile:			No
Generate Slugs on Directories:	Yes
Force UTF-8 Encoding: 		No
JS/CSS Compression: 			No
Port Forwarding in URL: 		No
Exclude CSS/JS on Home: 		No


--- UM Pages Configuration ---

User:						https://(redacted)/user/
Account:						https://(redacted)/account/
Members:					https://(redacted)/musicians/
Register:						https://(redacted)/no-access/
Login:						https://(redacted)/login/
Logout:						https://(redacted)/logout/
Password Reset:				https://(redacted)/password-reset/


--- UM Users Configuration ---

Default New User Role: 		0
Profile Permalink Base:		name
User Display Name:			full_name
Force Name to Uppercase:		No
Redirect author to profile: 		Yes
Enable Members Directory:	Yes
Use Gravatars: 				No
Require a strong password: 	Off


--- UM Access Configuration ---

Panic Key: 								
Global Site Access:						Site accessible to Logged In Users
Custom Redirect URL:						https://(redacted)/login/
Exclude the following URLs:				
Backend Login Screen for Guests:			No
Redirect to alternative login page:			
Backend Register Screen for Guests:		No
Redirect to alternative register page:		
Access Control widget for Admins only: 		No
Enable the Reset Password Limit:			No
Blacklist Words: 							5


--- UM Email Configurations ---

Mail appears from:  			GRYS&CO
Mail appears from address:  	(redacted)
Use HTML for E-mails:   		Yes
Account Welcome Email:  		No
Account Activation Email:   	No
Pending Review Email:   		No
Account Approved Email: 		No
Account Rejected Email: 		No
Account Deactivated Email:  	No
Account Deleted Email:  		No
Password Reset Email:   		Yes
Password Changed Email: 		Yes


--- UM Total Users ---

All Users(499)
administrator(8)
um_musician(74)
um_volunteer(6)
um_staff(4)
um_parent-guardian(123)
signup_sheet_manager(6)
um_new-parent(37)
um_audition-paid(7)
um_auditioning-parent(62)
um_audition-passed(29)
um_audition-failed(7)
um_former-musician(54)
um_former-parent(81)
um_returning-musician(61)
none(1)


--- UM Roles ---

Administrator (administrator)
Musician (um_musician)
Volunteer (um_volunteer)
Staff (um_staff)
Parent/Guardian (um_parent-guardian)
Sign-up Sheet Manager (signup_sheet_manager)
New Parent (um_new-parent)
Customer (customer)
Shop manager (shop_manager)
Audition Registered (um_audition-registered)
Audition Paid (um_audition-paid)
Auditioning Parent (um_auditioning-parent)
Audition Passed (um_audition-passed)
Audition Failed (um_audition-failed)
Former Musician (um_former-musician)
Former Parent (um_former-parent)
Returning Musician (um_returning-musician)


--- UM Custom Templates ---

N/A


--- UM Email HTML Templates ---

N/A


--- Web Server Configurations ---

PHP Version:              			7.2.30
MySQL Version:            			5.7.28
Web Server Info:          			Apache


--- PHP Configurations ---

PHP Memory Limit:         			256M
PHP Upload Max Size:      			400M
PHP Post Max Size:        			405M
PHP Upload Max Filesize:  			400M
PHP Time Limit:           			600
PHP Max Input Vars:       			1000
PHP Arg Separator:        			&
PHP Allow URL File Open:  			Yes


--- Web Server Extensions/Modules ---

DISPLAY ERRORS:           			N/A
FSOCKOPEN:                			Your server supports fsockopen.
cURL:                     			Your server supports cURL.
SOAP Client:              			Your server has the SOAP Client enabled.
SUHOSIN:                  			Your server does not have SUHOSIN installed.
GD Library:               			PHP GD library is installed on your web server.
Mail:                     			PHP mail function exist on your web server.
Exif:				          PHP Exif library is installed on your web server.


--- Session Configurations ---

Session:                  			Disabled
Session Name:             			PHPSESSID
Cookie Path:              			/
Save Path:                			/tmp
Use Cookies:              			On
Use Only Cookies:         			On


--- WordPress Active Plugins ---

Advanced Order Export For WooCommerce: 3.1.5
Contact Form 7: 5.2.2
Contact Form DB: 2.10.36
Easy Updates Manager: 9.0.6
GitHub Updater: 9.8.1
GRYS Member Site custom additions: 1.0
Import Users from CSV: 1.0.1
Kadence Blocks – Gutenberg Blocks for Page Builder Features: 1.8.13
Simple Calendar: 3.1.32
Simple Login Log: 1.1.3
SMTP Mailing Queue: 1.3.1
Ultimate Member: 2.1.8
Virtue/Ascend/Pinnacle Toolkit: 4.9.6
Volunteer Sign Up Sheets: 3.2.9
WooCommerce: 4.5.1
WordPress Importer: 0.7
WordPress Users & WooCommerce Customers Import Export(BASIC): 1.4.3
WP Maintenance Mode: 2.2.4
WP Reroute Email: 1.4.1

### End Install Info ###                    
```
</details>

Originally reported at https://wordpress.org/support/topic/after-2-1-update-roles-dropdown-returns-error-500-on-profile-form/

The changelog implies there was a security fix applied which caused this, but it's unclear what the security issue was that it's fixing.  Perhaps people were adding the role field to forms without restricting it to admin?

**Comment by justdave** [comment]
Here's the settings for the Role field that appears on the profile:

<img width="729" alt="Screen Shot 2020-09-10 at 12 16 46 PM" src="https://user-images.githubusercontent.com/307334/92761328-924a3180-f35f-11ea-9e28-9c40a4604061.png">

**Comment by nikitasinelnikov** [comment]
Hi @justdave

Could you provide what form_id is for this role field? There was a security fix in UM 2.1.9. You need to make some postmeta updates for the field options.
 
Let me know,
Thanks!

**Comment by nikitasinelnikov** [comment]
Hi @justdave 

Please check the latest Ultimate Member version. (commit https://github.com/ultimatemember/ultimatemember/commit/ec1db4f5cd0e7de80e574a2fd0fba071784e23b6)

Let me know how it works,
Thanks!

**Comment by guiyom-e** [comment]
I am afraid the code you added in `includes/core/class-form.php` raises again the security issue you fixed previously (which is a backend issue, not frontend). When specific member roles are defined, it is not sufficient to hide the role field in the frontend, it is necessary to check if the current user have the right to change the role when the POST query to edit profile is received. I have not investigated enough to know where it should be changed however.

I'm also not sure to understand all details in the code, but I don' get why `exclude_roles` are only wp_roles. I may want to change my role to a WP role, isn't it ? I think this restriction was already present in version 2.1.8.

**Comment by justdave** [comment]
How do I find the form_id?  I don't see anything called that in postmeta... unless you mean the post_id of the form in the posts table?

**Comment by Rzalexander** [comment]
I would also like to add that I don'tunderstand the "postmeta" comment either and would like to get this resolved. However, I was not able to get the registration fixed by rolling back to 2.1.8 and it is still broken for my users. 

What else needs to be done and is there documentation on this someplace so I can get this handled?

**Comment by nikitasinelnikov** [comment]
Hi @justdave , the issue is finally fixed in this commit:

https://github.com/ultimatemember/ultimatemember/commit/ec1db4f5cd0e7de80e574a2fd0fba071784e23b6

@guiyom-e the users are able to edit their roles in the case when the Administrator adds the visible Role (Dropdown/Radio) field to the Profile Form and users can edit their profiles. The limitation that we enforce is the roles that can be assigned to the user on the profile form.

Due to security restrictions, the user can choose from the list:
WP native Subscriber (it has "read" capability by default, there aren't wp-admin permissions)
All custom created UM roles. These roles can be customized (UM capabilities and WP capabilities also).

The roles list can be customized in the field's settings. So the choice of roles from the list is flexible enough, as are the role options. 

1. Ultimate Member plugin has a feature to create a custom UM roles. For all UM roles, there is possible to select WP Capabilities and it's true that some UM roles can have access to wp-admin or some other capabilities. But only if the administrator has configured the roles in this way.

https://www.screencast.com/t/j9vgFNdLn

2. The website Administrator has the ability to create a registration/user profile form with roles selector (radio or dropdown). For security reasons, there can be only WP native Subscriber and all custom UM roles as the "Role radio/select" field options.

https://www.screencast.com/t/cWxrCfrMFWX

3. There is possible to remove some roles from the field options. But even you manually add e.g. "Administrator" role here. It will be displayed, you haven't the ability to change your role to this.
4. We are checking $_POST['role'] in the forms handler:
- https://plugins.trac.wordpress.org/browser/ultimate-member/trunk/includes/core/class-form.php#L377-401
- custom_field_roles() - getting all roles keys from role-type custom fields at the form
- $exclude_roles = array_diff( array_keys( $wp_roles->roles ), array_merge( $role_keys, array( 'subscriber' ) ) ); - check that role in the $_POST is WP native Subscriber or UM custom role.

And I see this screen when trying to replace "subscriber" to "administrator" https://www.screencast.com/t/I8G6zSZ1l or another role, which isn't in the roles list.

@Rzalexander please check the latest version here https://downloads.wordpress.org/plugin/ultimate-member.2.1.10-rc.1.zip

**Comment by justdave** [comment]
Confirmed, it's working in 2.1.10 :)

Thanks!
