### ISSUE TITLE
Make UM forms possible in restricted access message

### ISSUE THREAD

**Issue by cswebdesigns** [ultimatemember/ultimatemember#784]
**Is your feature request related to a problem? Please describe.**
Smart way for restricted posts if the user can login and will be redirected to the post directly. Currently you have to link to the login page and then of course there is no redirecting to the post possible (active page = login page).

**Describe the solution you'd like**
Using login or registration form.

**Describe alternatives you've considered**
No sense fully alternatives possible.  

**Additional context**

**Comment by yuriinalivaiko** [comment]
Did you use the tool [UM Content Restriction](https://docs.ultimatemember.com/article/1543-how-to-hide-a-page-for-logged-out-users)? You can select an option **Redirect user** in the setting setting _"What happens when users without access tries to view the content?"_ and select an option **Login page** in the setting _"Where should users be redirected to?"_. In this case the browser will save the restricted page/post in the URL parameter _"redirect_to"_ and the user will be redirected back to the restricted page/post after login. 
Is it what you need?
