### ISSUE TITLE
Ned filter to enhance the functionality 

### ISSUE THREAD

**Issue by ajeetku** [ultimatemember/ultimatemember#872]
Hello team,
Related plugin: Real-time Notifications
We are adding compatibility of notification.
We need a filter/action on the time of store notification with notification details. 
After notification will be successfully submitted.

**Comment by champsupertramp** [comment]
Hi @ajeetku 

Please contact us via our website for premium extension support.

To submit a ticket, please login to our website using the email used on checkout and go to this page: 

 https://ultimatemember.com/support/ticket/ 

Regards,

**Comment by michael-newman** [comment]
@ajeetku, Please know I just submitted a ticket to UM requesting collaboration on the integration.

@champsupertramp, you should see the ticket come under Gil's name--If you could advocate for this integration within UM, that would be greatly appreciated.

Thank you both.

Regards, Mike

**Comment by ajeetku** [comment]
@michael-newman Thanks, we'll wait for their update

**Comment by michael-newman** [comment]
@ajeetku , I understand @champsupertramp added the two action hooks you requested in a pre-release version of the UM Real-time notification extension, and you both are in communication with each other.

At this point, I will consider you both connected to collaborate unless I hear otherwise.

Thank you both. Regards, Mike

**Comment by ajeetku** [comment]
@michael-newman Yes, we communicate. and added the compatibility.
Thanks for the quick solution and active response @champsupertramp, @michael-newman.
