### ISSUE TITLE
Breaking changes on action um_before_submit_form_post in patch 2.2.5

### ISSUE THREAD

**Issue by Xilonz** [ultimatemember/ultimatemember#945]
**Expected behavior**
We'd expect changes to filters be reported in the changelog and no especially no breaking changes in patches.

**Describe the bug**
The action `um_before_submit_form_post` got broken in patch 2.2.5, it no longer supplies $_POST to the action which caused major issues for us. The example for this hook is also incorrect, as it too still shows $_POST to be the first argument of the action.

Diff;
https://github.com/ultimatemember/ultimatemember/commit/0fc2d131ee2d41aa1baf9b5caa013be97e55b46b#diff-c92a97f27c3c4ca2989b774ff0ab56df2ed1debf45c3f78556948f44252274d7L351

**Comment by nikitasinelnikov** [comment]
Hi @Xilonz 

Thanks for letting us know! The `$_POST` argument is redundant for this hook. You may get it using $_POST inside your custom callback instead of the using callback argument variable.

`<?php
add_action( 'um_before_submit_form_post', 'my_before_submit_form_post', 10 );
function my_before_submit_form_post() {
    $post = $_POST;
    // your old code here
}
?>`

The hookdocs will be also updated soon.
Please mark this issue closed if the code above works on your website.
Best Regards!
